<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <UserSecretsId>f6105a9d-3f2d-4b5b-bea4-29a362a02857</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Crate.Core\Crate.Core.csproj" />
      <ProjectReference Include="..\Crate.Lambda\Crate.Lambda.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="11.0.0-preview.7.26381.103" />
      <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="11.0.0-preview.7.26381.103" />
    </ItemGroup>

</Project>
